import { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: '3D Printed Robot',
    description: 'Посмотри на это милое и забавное лицо!',
    price: 29.99,
    image: "/stickers/dog1.png",
    category: 'robots',
    inStock: true,
  },
  {
    id: '2',
    name: 'Dragon Figurine',
    description: 'Одно слово - прекрасно!',
    price: 39.99,
    image: "/stickers/dog1.png",
    category: 'fantasy',
    inStock: true,
  },
  {
    id: '3',
    name: 'Space Ship',
    description: 'Futuristic space ship model with LED lights.',
    price: 49.99,
    image: "/stickers/dog1.png",
    category: 'space',
    inStock: true,
  },
  {
    id: '4',
    name: 'Dinosaur Set',
    description: 'Set of 3 different dinosaur models.',
    price: 59.99,
    image: "/stickers/dog1.png",    category: 'dinosaurs',
    inStock: true,
  },
  {
    id: '5',
    name: 'Castle Model',
    description: 'У него точно есть свой личный стилист.',
    price: 69.99,
    image: "/stickers/dog1.png",    category: 'fantasy',
    inStock: true,
  },
  {
    id: 'dog-1',
    name: "Единорог",
    description: "Они существуют!",
    price: 9.99,
    image: "/stickers/dog1.png",
    category: 'stickers',
    inStock: true,
  },
  {
    id: 'dog-2',
    name: "Модник",
    description: "У него точно есть свой личный стилист.",
    price: 9.99,
    image: "/stickers/dog2.png",
    category: 'stickers',
    inStock: true,
  },
  {
    id: 'dog-3',
    name: "Слюнявчик",
    description: "Посмотри на это милое и забавное лицо!",
    price: 9.99,
    image: "/stickers/dog1.png",
    category: 'stickers',
    inStock: true,
  },
  {
    id: 'dog-4',
    name: "Путешественник",
    description: "Всегда готов к новой прогулке.",
    price: 9.99,
    image: "/stickers/dog2.png",
    category: 'stickers',
    inStock: true,
  },
  {
    id: 'dog-5',
    name: "Соня",
    description: "Сон — это жизнь.",
    price: 9.99,
    image: "/stickers/dog1.png",
    category: 'stickers',
    inStock: true,
  },
  {
    id: 'dog-6',
    name: "Гурман",
    description: "Сделает трюк за вкусняшку.",
    price: 9.99,
    image: "/stickers/dog2.png",
    category: 'stickers',
    inStock: true,
  }
]; 